### ISSUE TITLE
[Library] 라이브러리 적용 중 참고할 부분

### ISSUE THREAD

**Issue by Lautner-kwangho** [Lautner-kwangho/management#2]
# **라이브러리 특징 및 주의사항**

## **SwiftGen 특징 및 주의사항**
- Pod을 이용하여 설치한 뒤, `swiftgen.yml` 를 생성하여 적용해주는 명령어를 입력했지만  ```zsh: command not found: swiftgen``` 반환
- 해당 명령어 말고 ```./Pods/SwiftGen/bin/swiftgen config init``` 입력하면 정상적으로 생성 가능
  -> 출력값 : ```Example configuration file created: swiftgen.yml```
- 이후 프로젝트에 ```.yml``` 파일 추가 및 작성 한 뒤, 터미널에서 ```./Pods/SwiftGen/bin/swiftgen``` 명령어 실행
- 만약 리소스가 자주 변경된다면 Run Script를 이용하여 작성하면 된다

**Comment by Lautner-kwangho** [comment]
### 만약 ```.xcassets```을 분할하여 사용하고 싶을 때는 아래처럼 작성하면 된다
### 단, 여기서 주의할 점은 들여쓰기에 정말 민감해서 조심하도록 하자
### 올바른 작성법
```
xcassets:
  inputs: Assets.xcassets
  outputs:
    templateName: swift5
    output: Colors+Utils.swift
    params:
      forceProvidesNamespaces: true
      enumName: Colors

    inputs: Images.xcassets
    outputs:
      templateName: swift5
      output: Images+Utils.swift
      params:
        forceProvidesNamespaces: true
        enumName: Images
```

**Comment by Lautner-kwangho** [comment]
### 아래처럼 적을 경우, Image+Utils.swift 만 만들어진다!
### 틀린 작성법
```
xcassets:
  inputs: Assets.xcassets
  outputs:
    templateName: swift5
    output: Colors+Utils.swift
    params:
      forceProvidesNamespaces: true
      enumName: Colors

  inputs: Images.xcassets
  outputs:
    templateName: swift5
    output: Images+Utils.swift
    params:
      forceProvidesNamespaces: true
      enumName: Images
```
